import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, FileSpreadsheet, Inbox, LockKeyhole, MapPinned, Search, ShieldCheck, Sparkles, TreePine, Users } from 'lucide-react';
import { useAuth } from '../firebase/auth-context';

const EMBLEM='https://upload.wikimedia.org/wikipedia/commons/f/fe/Seal_of_Odisha.png';
type Stats={incoming:number;outgoing:number;total:number};

export function HomePage(){
 const {user}=useAuth(); const [stats,setStats]=useState<Stats|null>(null);
 useEffect(()=>{let dead=false;const load=async()=>{try{const r=await fetch('/api/public/stats',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();if(!dead&&d.ok)setStats({incoming:Number(d.incoming||0),outgoing:Number(d.outgoing||0),total:Number(d.total||0)})}catch{} };load();const id=window.setInterval(load,60000);return()=>{dead=true;window.clearInterval(id)}},[]);
 return <div className="home-page min-h-screen overflow-hidden bg-slate-50 text-slate-900"><div className="home-orb home-orb-one"/><div className="home-orb home-orb-two"/>
 <header className="sticky top-0 z-50 border-b border-white/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-3.5 sm:px-6"><Link to="/" className="flex min-w-0 items-center gap-3"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-emerald-100 bg-white shadow-sm"><img src={EMBLEM} alt="Government of Odisha emblem" className="h-10 w-10 object-contain"/></span><span className="min-w-0"><b className="block truncate text-sm text-emerald-950 sm:text-base">Forest, Environment &amp; Climate Change Department</b><span className="block truncate text-xs font-semibold text-slate-500 sm:text-sm">Govt of Odisha · Forest Range Office, Kodinga</span></span></Link><div className="flex items-center gap-2">{user?<Link to="/dashboard" className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white">Open Dashboard <ArrowRight size={16}/></Link>:<><Link to="/range-information" className="hidden rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-sm font-bold text-emerald-900 sm:inline-flex">Range Information</Link><Link to="/login" className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white">Sign In</Link></>}</div></div></header>
 <main><section className="mx-auto grid max-w-7xl items-center gap-12 px-5 pb-16 pt-12 sm:px-6 md:pb-24 md:pt-16 lg:grid-cols-[1.05fr_.95fr]"><div className="relative z-10"><div className="home-fade-up inline-flex items-center gap-2 rounded-full border border-emerald-100 bg-white/80 px-3.5 py-2 text-xs font-bold uppercase tracking-[.12em] text-emerald-700 shadow-sm"><Sparkles size={14}/> Digital Forest Range Office</div><h1 className="home-fade-up home-delay-1 mt-6 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl md:text-6xl md:leading-[1.03]">One digital home for <span className="block bg-gradient-to-r from-emerald-700 via-teal-700 to-slate-950 bg-clip-text text-transparent">Kodinga Range.</span></h1><p className="home-fade-up home-delay-2 mt-6 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">Manage official correspondence securely and explore public Kodinga Range information — Sections, Beats, forests, plantations, villages, nurseries, VSS, fire points and more.</p><div className="mt-8 flex flex-wrap gap-3">{user?<Link to="/dashboard" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3.5 font-bold text-white shadow-lg">Continue to Office Register <ArrowRight size={18}/></Link>:<><Link to="/signup" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3.5 font-bold text-white shadow-lg">Register <ArrowRight size={18}/></Link><Link to="/range-information" className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-white px-5 py-3.5 font-bold text-emerald-900 shadow-sm"><MapPinned size={18}/> Range Information Centre</Link></>}</div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-slate-500"><span><span className="home-status-dot mr-2 inline-block"/>Public information</span><span><LockKeyhole size={15} className="mr-2 inline"/>Secure office access</span><span><FileSpreadsheet size={15} className="mr-2 inline"/>Reports &amp; exports</span></div></div>
 <div className="relative z-10 rounded-[2rem] border border-white bg-white/90 p-5 shadow-2xl shadow-emerald-950/10 backdrop-blur-xl sm:p-6"><div className="rounded-[1.5rem] bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-wider text-emerald-300">Kodinga Range</p><h2 className="mt-2 text-2xl font-black">Information at a glance</h2><div className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><TreePine size={20}/><p className="mt-3 text-3xl font-black">2</p><p className="text-xs text-slate-300">Sections</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><Users size={20}/><p className="mt-3 text-3xl font-black">6</p><p className="text-xs text-slate-300">Beats</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><MapPinned size={20}/><p className="mt-3 text-3xl font-black">29</p><p className="text-xs text-slate-300">Information sheets</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><Search size={20}/><p className="mt-3 text-3xl font-black">{stats?.total??'—'}</p><p className="text-xs text-slate-300">Register records</p></div></div></div><div className="mt-4 grid grid-cols-2 gap-3"><Link to="/range-information" className="rounded-2xl border border-emerald-100 bg-emerald-50 p-4 transition hover:-translate-y-0.5"><MapPinned className="text-emerald-700" size={20}/><p className="mt-3 text-sm font-extrabold">Explore Range Information</p><p className="mt-1 text-xs text-slate-500">Public access</p></Link><Link to={user?'/dashboard':'/signup'} className="rounded-2xl border border-blue-100 bg-blue-50 p-4 transition hover:-translate-y-0.5"><BookOpen className="text-blue-700" size={20}/><p className="mt-3 text-sm font-extrabold">{user?'Office Register':'Register an account'}</p><p className="mt-1 text-xs text-slate-500">{user?'Authenticated workspace':'Download &amp; print access'}</p></Link></div></div></section>
 <section className="border-y border-slate-200 bg-white/80"><div className="mx-auto grid max-w-7xl gap-px px-5 sm:px-6 md:grid-cols-3"><Link to="/range-information" className="p-8 transition hover:bg-emerald-50/40"><MapPinned className="text-emerald-700"/><h2 className="mt-4 font-extrabold">Range Information Centre</h2><p className="mt-2 text-sm leading-6 text-slate-500">Open public access to the Range's forest, village, plantation, nursery, VSS and protection information.</p></Link><Link to={user?'/dashboard':'/login'} className="border-slate-200 p-8 transition hover:bg-blue-50/40 md:border-x"><Inbox className="text-blue-700"/><h2 className="mt-4 font-extrabold">Office Letter Register</h2><p className="mt-2 text-sm leading-6 text-slate-500">Manage Incoming Dak and Outgoing Letters with controlled office access.</p></Link><Link to={user?'/reports':'/signup'} className="p-8 transition hover:bg-indigo-50/40"><ShieldCheck className="text-indigo-700"/><h2 className="mt-4 font-extrabold">Registered User Access</h2><p className="mt-2 text-sm leading-6 text-slate-500">Registered users can generate reports, exports, prints and Range handbooks.</p></Link></div></section></main>
 <footer className="border-t border-slate-200 bg-white/80"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-5 py-7 text-sm sm:px-6 md:flex-row"><span className="flex items-center gap-3 text-slate-500"><img src={EMBLEM} alt="" className="h-8 w-8 object-contain"/>Forest Range Office, Kodinga · Govt of Odisha</span><nav className="flex gap-5 font-semibold text-emerald-700"><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/range-information">Range Information</Link></nav></div></footer>
 </div>;
}
